name: Debug Check Run

on:
  check_suite:
    types: [created, rerequested, completed]

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo '${{ toJson(github.event) }}'

# name: Test Netlify Preview

# on:
#   check_run:
#     types: [completed]

# jobs:
#   test-preview:
#     if: |
#       github.event.check_run.name == 'Netlify' &&
#       github.event.check_run.conclusion == 'success'

#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         path:
#           - /
#           - /welcome
#           - /api/test
#           - /404

#     steps:
#       - name: Get preview URL
#         run: |
#           echo "URL=https://deploy-preview---lucent-marshmallow-a6250f.netlify.app" >> $GITHUB_ENV

#       - name: Check URL
#         run: |
#           STATUS=$(curl -s -o /dev/null -w "%{http_code}" "${{ env.URL }}${{ matrix.path }}")
#           echo "${{ env.URL }}${{ matrix.path }} -> $STATUS"

#           if [ "$STATUS" != "200" ]; then
#             echo "Expected 200 but got $STATUS"
#             exit 1
#           fi
